language: python
python:
  - "3.7.4"
cache:
  pip: true
  directories:
    - build

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
        - COV=gcov-8
      
before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sudo ln -s "/usr/bin/${CC}" /usr/local/bin/gcc
  - sudo ln -s "/usr/bin/${CXX}" /usr/local/bin/g++

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v
  - pip install cpp-coveralls python-coveralls

script:
  - poetry run pylint snmp_fetch tests
  - poetry run flake8 snmp_fetch tests
  - poetry run mypy -p snmp_fetch -p tests
  - poetry run bandit -r snmp_fetch
  - poetry run pytest -v --cov --hypothesis-show-statistics tests/
